keycloak:
  fullnameOverride: gepardec-sso
  image: ghcr.io/gepaplexx-demos/gepardec-sso:latest
  ingress:
    hostname: gepardec-sso-kc-dev.apps.play.gepaplexx.com
  provider:
    openshift:
      enabled: false
  features:
    disabled: ""

  persistence:
    auth:
      password: "AgA1tpH9Mp+ebTqwg63mtfY394kbj7vcmRa14JkMSop1uSFWKPOO+XCAQyhUtmm3BNJB+CExx8WVJ8AtObXHbkTcHqDn6a2oRUWAfGFVvKCFLCBYx9Ag9beoQJuJov40j32G+R1o59UksvynD6SCg5/jtCc+F0TpBfOUL9c//9PSMQtC21HTZEzFiNTzhpAVP7bFl79EgiM6o3NmNa4QhWsOW6dO+vF/ZUGCMTaynuRCgg5LAttDgNjoLf1H9SpW0Gb6vu/RP/hkwnkbK9N+cB+TeO9zzrFxk8vBlm2YalG1e5lgpvKe3pQkKymV5kp+vnN9ZDUUpKE0VyhBB1YyYRhrWHWTmcf5s5ZMtI79xELVuGDN/3qPJkSWIZF4tNHgJYrphiMz4jrsjM43r1FS6cP371CATQ2s2DSxNjqtlBEKzFnPR7LfGfP2uzSqZyZQiz33pPQngvzG1k8PqGOMywUItyMpFm4JC3tVMYPuk/kOrpahykABNU+ZKxd+GNlqA4PM0V/XG0DxROh2XTZfpFcTOJcCofmy86FfvnbvOM+Zbcle9l/VXmKnbqnL+qEu5SzsfklN8MZ0buFB0N+OwBrHpk2SnScNuaaJQNIOHPaxyvGgvH4QSQXrQcPe5seR2zpFJoRt6nMfhmCvoTyErbMoES9dAcuxFsYCGbd0wJPfR52k9ERnJyFbW6ZKaB5QrOU04p5HpjXX/g=="
  postgresql:
    fullnameOverride: &dbName "gepardec-sso-db"
    auth:
      existingSecret: *dbName
db:
  backup:
    schedule: '0 0 * * *'
    retain:
      days: 8 # need to +1, so 7 days = 8