apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gepardec-sso
  namespace: gepaplexx-cicd-tools
spec:
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  destinations:
    - namespace: '*'
      server: '*'
  sourceRepos:
    - '*'
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: gepardec-sso-config
  namespace: gepaplexx-cicd-tools
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: gepardec-sso
  source:
    path: config
    repoURL: https://github.com/gepaplexx-demos/gepardec-sso-ci.git
    targetRevision: main
  project: gepardec-sso
  syncPolicy:
    automated:
      prune: true
      allowEmpty: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true