kind: Role
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-deployer
  namespace: gepardec-sso-qa
rules:
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - ''
    resources:
      - secrets
      - serviceaccounts
      - services
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - 'apps'
    resources:
      - deployments
      - replicasets
      - statefulsets
  - verbs:
      - create
      - delete
      - deletecollection
      - get
      - list
      - patch
      - update
      - watch
    apiGroups:
      - 'route.openshift.io'
    resources:
      - routes
  - verbs:
      - create
    apiGroups:
      - 'route.openshift.io'
    resources:
      - routes/custom-host



---

kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: custom-deployer
  namespace: gepardec-sso-qa
subjects:
  - kind: ServiceAccount
    name: deployer
    namespace: mega-backend-qa
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: custom-deployer

