kind: Secret
apiVersion: v1
metadata:
  name: keycloak-config
  namespace: gepardec-sso-qa
immutable: false
data:
  password: --secret-- #db_password in vault
  postgres-password: --secret--
  username: keycloak
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: keycloak-secret
  namespace: gepardec-sso-qa
data:
  KEYCLOAK_ADMIN: --
  KC_DB_USERNAME: --
  KC_HTTP_ENABLED: dHJ1ZQ==
  KC_DB_PASSWORD: --
  KC_DB_URL: >-
    --
  KEYCLOAK_ADMIN_PASSWORD: --
  KC_HTTPS_PORT: NDQz
type: Opaque

