###TODO Find out why setting a password for the Postgres database only works by defining it with this secret
###More info about the password issue in the values.yaml

kind: Secret
apiVersion: v1
metadata:
  name: keycloak-config
  namespace: gepardec-sso-qa
immutable: false
data:
  ###DON'T CHECK IN ACTUAL VALUES!!!
  password: --secret-- #db_password in vault
  postgres-password: --secret--
  username: keycloak
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: keycloak-secret
  namespace: gepardec-sso-qa
data:
  # base64 encoded dHJ1ZQ== decodes to true. This is done to have valid base64 encoded values in the secret inorder to avoid errors when deploying
  # No actual values are stored in the secret, DON'T CHECK IN ACTUAL VALUES!!!
  KEYCLOAK_ADMIN: dHJ1ZQ==
  KC_HOSTNAME_URL: >-
    dHJ1ZQ==
  KC_DB_USERNAME: dHJ1ZQ==
  KC_HTTP_ENABLED: dHJ1ZQ==
  KC_DB_PASSWORD: dHJ1ZQ==
  KC_DB_PASSWORD_USER: dHJ1ZQ==
  KC_DB_URL: dHJ1ZQ==
  KEYCLOAK_ADMIN_PASSWORD: dHJ1ZQ==
  KC_HOSTNAME_ADMIN_URL: >-
    dHJ1ZQ==
  KC_HTTPS_PORT: NDQz
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: gepardec-sso-dockercfg
  namespace: gepardec-sso-qa
data:
  ###DON'T CHECK IN ACTUAL VALUES!!!
  .dockercfg: >-
    dHJ1ZQ==
type: kubernetes.io/dockercfg


