kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: {{ .Values.db.backup.name }}
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: "10Gi"
  volumeMode: Filesystem
  storageClassName: rook-ceph-fs