kind: Secret
apiVersion: v1
metadata:
  name: keycloak-secret
  namespace: gepardec-sso-prod
data:
  # Dummy values for secrets are base64 encoded too. This is done to have valid base64 encoded values in the secret inorder to avoid errors when applying
  # No actual values are stored in the secret, DON'T CHECK IN ACTUAL VALUES!!!
  # admin
  KEYCLOAK_ADMIN: YWRtaW4=
  # https://gepardec-sso-prod.apps.cloudscale-lpg-2.appuio.cloud
  KC_HOSTNAME_URL: >-
    aHR0cHM6Ly9nZXBhcmRlYy1zc28tcHJvZC5hcHBzLmNsb3Vkc2NhbGUtbHBnLTIuYXBwdWlvLmNsb3Vk
  # keycloak
  KC_DB_USERNAME: a2V5Y2xvYWs=
  # true
  KC_HTTP_ENABLED: dHJ1ZQ==
  # change me
  KC_DB_PASSWORD: Y2hhbmdlbWU=
  # jdbc:postgresql://postgresql-keycloak:5432/keycloak
  KC_DB_URL: amRiYzpwb3N0Z3Jlc3FsOi8vcG9zdGdyZXNxbC1rZXljbG9hazo1NDMyL2tleWNsb2Fr
  # change me
  KEYCLOAK_ADMIN_PASSWORD: Y2hhbmdlbWU=
  # https://gepardec-sso-prod.apps.cloudscale-lpg-2.appuio.cloud
  KC_HOSTNAME_ADMIN_URL: >-
    aHR0cHM6Ly9nZXBhcmRlYy1zc28tcHJvZC5hcHBzLmNsb3Vkc2NhbGUtbHBnLTIuYXBwdWlvLmNsb3Vk
  # 443
  KC_HTTPS_PORT: NDQz
type: Opaque

---

kind: Secret
apiVersion: v1
metadata:
  name: google-oauth-credentials
  namespace: gepardec-sso-prod
immutable: false
data:
  #should be in format of:
  # GOOGLE_CLIENT_ID=<secret>.apps.googleusercontent.com
  # GOOGLE_CLIENT_SECRET=<secret>
  secrets.properties: >-
    R09PR0xFX0NMSUVOVF9JRD08c2VjcmV0Pi5hcHBzLmdvb2dsZXVzZXJjb250ZW50LmNvbQpHT09HTEVfQ0xJRU5UX1NFQ1JFVD08c2VjcmV0Pg==
type: Opaque


