kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "gepardec-sso.fullname" . }}
  labels:
      {{- include "gepardec-sso.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "gepardec-sso.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Allow
    key: |-
      -----BEGIN PRIVATE KEY-----
      MIIJQwIBADANBgkqhkiG9w0BAQEFAASCCS0wggkpAgEAAoICAQCoWaMZGjfK+J3e
      C0ByNPjtyEMVT0kUF8wyRwfoXtWWFOOMgqJ2BTHhAhHJXJinERhGUEfKGgZLCEsv
      ZkDttc6rNVRjRkKS/MG2MCmY4VQrYMBgDC7SMEF+U1n0pCw+B8f++GGY5xUKhPZk
      hnBCoMmBww7XNDehKsUW36HNXlv11+Xw1KB2aLcEK/TWbrxLTGegrbMezJII0I1i
      btTRHf5mCOsKaD6nKqDbVi6nsochscrzzBLVWfXBVLjrI5MXOnoqTWTL+aKYRGwt
      SkSr13q37Ev7grCeSJl6rS0sW543muaDIxp01/2ko/oj6gJ7cttTyXa6sqM4W0R6
      e4l99x17xg96onS/9YmlzFngmRaPU38XYpTGbSCw4kbmZ0UJVw+r6etC1YJNTNLy
      BugE8R+5tiVqUdzk2LeeuSyidwqzmNU+QPXpDYGaj/BiVzf2iR4rBgLzQ6KBed1M
      5VDMG+iMrVSl4yIvSfGPhcpLh5oUs42dkbWtj2OGdEXZ1I6J30iyGQLYq6ffYnlL
      C7fVm8o2XFMG8QG99StZC1MgJhpdkIuX0kcBRMnjIGZB48cKjrLyB02ASWrs7atI
      Qpftyt0QNLGJx43Pc2sAI3Je9XZUqm+cqXYqrdWGL+PqSp661vz5q8lvm3eK599O
      +BAXirqrzr8T6MTDLRAv+LJ51jEbRQIDAQABAoICAQCNoTOcZ7kucfBmIHMsYbJW
      YRdGszgYxliMp8NYU4g+xf4VdMV2orIuyQ3rqJHoY3JXnSx4M2K99xFBpDXVhhGD
      ac8/4ZkajbfuLSChtFeaUsAlTbqKK/y9aSQRs5hg6yzvLUj2WNoTyn57XbrN4vUD
      zPUMSarPVOsQbj1ySAL3lZWmAUupsjjeMpi9WdXhRzsbK2a474OgFMwNVo6GC0S9
      1JzgWYj0G+HOBPglLwWObEQAzNu/T/p3lm4nq/sQHKswMYIuNCr9DPsxMv0I0LQ2
      TX4y7uTllNBCK7UIT1+RCikJhBu61wdVXnqPgkxqTNuF5sSTFrxIKkg2/v1R0vai
      j/vLxM3xMUoi1HhFUe/jtLustJGrhf+5h07F3y01c+0Jl0YjZkRubNZz0iDHO8qz
      8SkX204CdoCVgrHY3XqzhRpzkopuQAlSfU9OQxYxk9GeZvPnpYn9SupbgedeZbWH
      3wVqSy++Wwf5+ZJBl8alc6qHSjsBwV0si6lhtADB3rm1faNcvj1vFpKKhGdBi4TP
      sWDUFSJILUToqONNY6G4r7a7Hi7EkwzBK5WVkflCWqG1i0L+KLZEuHfKx1a2Gf+C
      gAlQrIUy+/AOfk3qom4MtfzIq8A8p7tHr5jgfLreo2AoOEUZ8ozRZlllZhNiWgFf
      FXCX3eYqVlY7/o613RSZdQKCAQEA2RTHS7OfdhzpUY5uQeUA9y2ZY4dCyzdhdgoQ
      p+dKBR5qBrXLE45XWZC5Z2wQSAchKlmKtw8HBAbI7tXLlfgc1dnytUKBC7d6hBea
      o/XH3NMa/uyQlTmhhDUqMTtcBOQ8JwEtQLIiL5EQPxlaa8XWO5qPlrdya5P/MapC
      MHlxVFAXJNajPukOdGelBdT0DkiIOHt0R1YpWq94imnFEOv91bQi2v8HJt1Kb71O
      tskWjwomX+jdDeRp/2a/GTb9ecpIIcq985qHITUv/b8jUHHqIKmRwJf5LgcQehAE
      5sCjPg4yVe83EHCaC5d/RAzSoaUYP8LwwPxPQnnyCIJd00ihGwKCAQEAxohJBGxm
      FpOHea4NRbAchYsHLU+MclrnBX4d5cwTLesolLe6bA0FcEMYfo1dp0WIlDR4Nr/k
      SEzgml1SwJKU+sYZnQKs0ihQS4FcYZ2tV7s1IhE+IzzUqctDfy4m5RukyAepPHgm
      pWL6AYVoKw2HtngydUhwGREV3IAp4AhYq/oAerHWNHcG4iDkPc80Idge6XO6qLZJ
      QHsPYumPDcZaHUBQXBkvOxAl5CwUu9zLfNovEreNkteuU6rEei0sxGbVioO6CBDL
      8ckm8KG1xF+36CN/Md9if6At+pSyoN4ZiX7GG4rSb+0Xujzmrz/58x6R3CoyKObg
      1T+74UVXMHNbHwKCAQEAnrKhDAex0OBL9dKBamznKszMMUXGH9hJyMiM6qKcq2dT
      rbojTxWlaBX0ZNZMhMuphFNXpII458mqBWiI4Ac11WTzGW4X9x/YUk8LP0hEJ3yx
      ZKI/BMjP+l3/jWRO3kiYbQ9gLMbNVSbg0LBROS61cneI927/GARm8MD+iH+PyUqP
      0N+VEj3A0nqe2seW8AY4h8pA9JHZw7E6Fz5B0iAkPqHlRWJhsRjf/RZRQDF763BJ
      I56SVECi+RL9K4rW/b1SxFl6Smey2CURA5lDUOEmf2BX7IttoCeL9SBW5Pb5oDky
      tT4fbEZVZ5oGcRJKvd96/coexYbuzrNlrLDZtMeI9wKCAQAQFSg9GH7oo0jdPZFL
      rOmSk+Gf9Qq+lMiUNFQ9slt3Y85kxcFvUVq4bmcEkXUdwM9AmkOGw+K9TKUBPEAg
      4374FaYrhvTzDVr70t3l9nz9V2gFe3oaJqpfmty758Q02RlvLtex01XmHe98wg7f
      NfhherkzsQuLrEumEifSQzrTq6vwRInCtEW1ec6jhy6E81oFtV9QnXuvoohrjdoN
      1pykM/qOi2e9FCDNrBh943QEiDQ6Au6QD7LKilHiR9iRjHcOAn/GeX3b91yVL7Rm
      1Q4z2vRJ2PvEtPgkjXku+O7+qWto/cTwVjeO2bIiTj90R2yvdiecEp/yBni01gYr
      IZ0nAoIBAA2aewJMN7CUIeo1OxqFKMx8HHJ17R4b7zsHADV8GG2a8pClf1kwPCet
      Cf6U/8cMclRzhR7+QTkE5AKeBFbio1mtRwZoQrRw4Ko0MnDfkMapWV8ib83nGNIB
      OQMywiIlOF480DjQn0dQBJQFfX1227wWY6N6GYOmlulskNDjmRuP+JMmaOhqFsWt
      A6BlK7fxQgQYZBlomBd+LpBs4vn8RSodxau8O+GikPkTIcAFE98+ulqKNUFez5ZU
      7fAXIKSYIpnCmu06N7WTX+ioX/kIBYKSmVYTSCT53K2Oh1HY3VLz1Symqx+FBY8/
      mojpm5pjAoOaabJ4vBQIJS+2UcYxiIA=
      -----END PRIVATE KEY-----
    certificate: |-
      -----BEGIN CERTIFICATE-----
      MIIFGTCCAwECCQDtfMSIaCkepzANBgkqhkiG9w0BAQsFADBVMQswCQYDVQQGEwJB
      VDEPMA0GA1UECAwGVmllbm5hMQ8wDQYDVQQHDAZWaWVubmExETAPBgNVBAoMCEdl
      cGFyZGVjMREwDwYDVQQDDAhHZXBhcmRlYzAeFw0yNDA2MjQwODI4MjRaFw0yNDA3
      MjQwODI4MjRaMEgxCzAJBgNVBAYTAkFUMQ8wDQYDVQQIDAZWaWVubmExDzANBgNV
      BAcMBlZpZW5uYTEXMBUGA1UEAwwOKi5hcHB1aW8uY2xvdWQwggIiMA0GCSqGSIb3
      DQEBAQUAA4ICDwAwggIKAoICAQCoWaMZGjfK+J3eC0ByNPjtyEMVT0kUF8wyRwfo
      XtWWFOOMgqJ2BTHhAhHJXJinERhGUEfKGgZLCEsvZkDttc6rNVRjRkKS/MG2MCmY
      4VQrYMBgDC7SMEF+U1n0pCw+B8f++GGY5xUKhPZkhnBCoMmBww7XNDehKsUW36HN
      Xlv11+Xw1KB2aLcEK/TWbrxLTGegrbMezJII0I1ibtTRHf5mCOsKaD6nKqDbVi6n
      sochscrzzBLVWfXBVLjrI5MXOnoqTWTL+aKYRGwtSkSr13q37Ev7grCeSJl6rS0s
      W543muaDIxp01/2ko/oj6gJ7cttTyXa6sqM4W0R6e4l99x17xg96onS/9YmlzFng
      mRaPU38XYpTGbSCw4kbmZ0UJVw+r6etC1YJNTNLyBugE8R+5tiVqUdzk2LeeuSyi
      dwqzmNU+QPXpDYGaj/BiVzf2iR4rBgLzQ6KBed1M5VDMG+iMrVSl4yIvSfGPhcpL
      h5oUs42dkbWtj2OGdEXZ1I6J30iyGQLYq6ffYnlLC7fVm8o2XFMG8QG99StZC1Mg
      JhpdkIuX0kcBRMnjIGZB48cKjrLyB02ASWrs7atIQpftyt0QNLGJx43Pc2sAI3Je
      9XZUqm+cqXYqrdWGL+PqSp661vz5q8lvm3eK599O+BAXirqrzr8T6MTDLRAv+LJ5
      1jEbRQIDAQABMA0GCSqGSIb3DQEBCwUAA4ICAQAnwAqTzg1TRBPzZIXJGnbRJUOX
      csYWL82HOYk6rig7Oi/8ugaxSodBoZt/M/6L1g49gdEuVck3DaZ5+HKbrpIjofrS
      MfZZ2TuqLB/dyUssTxSP1Jr9M0YCbstdSlZlblJGVVFzxb2jciByW8k6kBxF9lZo
      ft716RsfPCq3XnFNe/XKPDeGx4OqkYaVNh0mAfOF1x+UxOhCX1N0VMaDPTYAJcFL
      m2ZTFkMGkUB+2ycQBl8T4F6hjA66x/0fOAdACod4C2p0xuTD97/rh7eNlSQF0fTC
      8Q9Ua+ia/wQMEc8EwPrcBz3iageB9gBMPmnIyjdTbM2n7wPFwMWO48mjpbFwh/im
      Bm1tEn5ChKCJNAIkNqySbXcVtRLW8dzzFT/ZP+aNyrtp71YAOBduQ7U3OIhAe8V4
      eDcaq4kSQ1gu79cGdyK1d/5XkgVWHljKGrtCqmf+s57ZLsqBlRdpx8Olv0GLcFOK
      RObfL/OcBJm361t56zJmpPkiGaKYfNr+VNKufmJnvRtTq32cVNn7rXXrdqhBZndz
      kbFUmfn/oPUyiFVhiQATofukUU0Huz4Oys/naOak/HAUJV44C874AouRwXNWbDpO
      LBOqNu20ZZrUY7EnUGvM+6E8xgOih7G7j5H1Qic6E4uTsGYTEdUkYRP7n/Uapd7Q
      nRVBtZQ+hnfykcThhQ==
      -----END CERTIFICATE-----
    destinationCACertificate: |-
      -----BEGIN CERTIFICATE-----
      MIIFJjCCAw4CCQDdE0vf6Z5eTzANBgkqhkiG9w0BAQsFADBVMQswCQYDVQQGEwJB
      VDEPMA0GA1UECAwGVmllbm5hMQ8wDQYDVQQHDAZWaWVubmExETAPBgNVBAoMCEdl
      cGFyZGVjMREwDwYDVQQDDAhHZXBhcmRlYzAeFw0yNDA2MjAwODA0MzdaFw0yNTA2
      MjAwODA0MzdaMFUxCzAJBgNVBAYTAkFUMQ8wDQYDVQQIDAZWaWVubmExDzANBgNV
      BAcMBlZpZW5uYTERMA8GA1UECgwIR2VwYXJkZWMxETAPBgNVBAMMCEdlcGFyZGVj
      MIICIjANBgkqhkiG9w0BAQEFAAOCAg8AMIICCgKCAgEA53l+LcMJ8kCh/TAL15cU
      12MI6QFx8yiX11wyrYbiFo0/imu26aq5nstvzGcX0LO/wiGPHDOenhFBicm5jcPJ
      KFBfij5abn12BcOLk7+/XKmMyWlIV5GZVIw+8KfSP/Itjr1YOeA2CSIqh4F5c0A/
      fTcVb+yQGzAcicTx5CIrist5Y8CqfhXQEP33Pu9BadQLuZ+sVAR8no89yxcdkVNP
      ft3lGDXDZSrYCXmkF69MqMC2rUC6KilS84AgYkKa4ck+AjLp3NTEbYaz1x+3Joza
      Q+wlhC7+KmiokP6pkot2r84UHEGNzp8+e6ITi58rBGHoq5XHDc1VNyFoUJTK6cwK
      UIXsxl1M+/tIJBjadZ6LonfnE4ILq7Ny57WLh2sj8ZGvkjM6B61MEiWot6Vga2TK
      qbXDR9mX5WaVzjV266RG88gamHIcmJbOGU2B2xvc75dsfDNT1z6oxPJIxiAFAbje
      ndn4pf6LA7ishcOjpUQ/JeWu+RnqLkdNW438fpex/GjZAaSDHk1HUkNwB8mcpzMK
      pq+19VObeLkURfxNIcOULgcDfhKj6zxDSh5qT93Ov41gskukx7x1DBma4PBPJ+qr
      Cq4svx/p3P9XqCRxT/uv7kqFuUFblaCueEYqFMpEKVCA8/+4QGRaKqaFqP9dzsJc
      jn+dJ9htQEsawONpl97ecn8CAwEAATANBgkqhkiG9w0BAQsFAAOCAgEANLzXiu0W
      uiS4x/2QSAaGpsej48rXNQ1RgtmEODOyl3P9igAajMK89tjK19sCigK1tRk3Kl7l
      ATCRIAk5We97LYQU6zBJktu4fp3iLHz8uuUIaYGy/f/hkvTXZFkwidjcumcGPkAI
      zGTeXsRg6aIzrhRDc93HUiU3+Q6QwidvV3aPwBPJv/jjXQqBaGIo1lBpsRaen2qe
      PKKExLn84qreqSBnxq2uAdrZUtl01XsDgPBkb+efc4+DhEZ2349v0ifznXYsj+ta
      MhGjz98+1ckVsv971zTx53pBXxL2jB9K894Eo2kDVrme2Drdoiqm1r/quLEFXZmp
      YVZdCvACwfvlxE0Ug4B1AcyF1cJM+FTGoLbfgQvsRUETC6rVW/EMyI0IHioxSNHg
      UGXSwwbqTutOVEV6bJnMJukx1FLa/d/cT5VaDlTofYkmMinTNGjZJ16WBEaMOm6I
      +/5qP4gXuhqMpPFmBoDekRyQS/zGG9ss6Ccog2t+kzfgWmvpoOMcbauE09Ai3T10
      Qv2/lGvbZW4bzOUBbgbsPFfE/2Tqoobw+rTxJADeKvl+tbeCKaBUeUc9PdvBc8O1
      DP45NIO9v/r3d7AYTf/qLKcznfypzkeSsUi1uzT8/xUvpIWJO7Uvs+oAJKfOketk
      2D2mqleyBzzDT01qMe3d5Rx1X00sxMk+KSY=
      -----END CERTIFICATE-----
  wildcardPolicy: None

