kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: {{ include "gepardec-sso.fullname" . }}
  labels:
      {{- include "gepardec-sso.labels" . | nindent 4 }}
spec:
  host: {{ .Values.route.host }}
  to:
    kind: Service
    name: {{ include "gepardec-sso.fullname" . }}
    weight: 100
  port:
    targetPort: http
  tls:
    termination: reencrypt
    insecureEdgeTerminationPolicy: Allow
  wildcardPolicy: None

