apiVersion: v1
kind: Service
metadata:
  name: {{ include "gepardec-sso.fullname" . }}
  annotations:
    service.beta.openshift.io/serving-cert-secret-name: {{ include "gepardec-sso.fullname" . }}
  labels:
    {{- include "gepardec-sso.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  internalTrafficPolicy: Cluster
  ports:
    - name: http
      port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
    - name: https
      port: 443
      targetPort: https
      protocol: TCP
  selector:
    {{- include "gepardec-sso.selectorLabels" . | nindent 4 }}


