kind: Job
apiVersion: batch/v1
metadata:
  generateName: gepardec-sso-keycloak-config-importer #dynamic
  labels:
    app: gepardec-sso #dynamic
  annotations:
    argocd.argoproj.io/hook: PostSync
    argocd.argoproj.io/hook-delete-policy: HookSucceeded
spec:
  parallelism: 1
  completions: 1
  template:
    metadata:
      labels:
        app: gepardec-sso #dynamic
        job-name: keycloak-config-importer
    spec:
      volumes:
        - name: config-data
          configMap:
            name: gepardec-sso-config #dynamic
        - name: secret-data
          secret:
            secretName: identity-prov-secrets #dynamic
      containers:
        - name: keycloak-config-cli
          image: 'docker.io/adorsys/keycloak-config-cli:5.3.1-19.0.1'
          imagePullPolicy: IfNotPresent
          terminationMessagePolicy: File
          terminationMessagePath: /log/termination-log
          env:
            - name: KEYCLOAK_SSLVERIFY
              value: "false"
            - name: IMPORT_FILES
              value: "/config/*"
            - name: KEYCLOAK_CONNECTTIMEOUT
              value: "10s"
            - name: KEYCLOAK_READTIMEOUT
              value: "10s"
            - name: KEYCLOAK_AVAILABILITYCHECK_ENABLED
              value: "true"
            - name: KEYCLOAK_AVAILABILITYCHECK_TIMEOUT
              value: "120s"
            - name: IMPORT_VARSUBSTITUTION_ENABLED
              value: "true"
            - name: IMPORT_VALIDATE
              value: "true"
            - name: IMPORT_CACHE_ENABLED
              value: "false"
            - name: KEYCLOAK_URL
              value: "https://sso-service:8443" #dynamic
            - name: KEYCLOAK_USER
              valueFrom:
                secretKeyRef:
                  name: sso-initial-admin #dynamic but from operator
                  key: username
            - name: KEYCLOAK_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: sso-initial-admin #dynamic but from operator
                  key: password
          volumeMounts:
            - name: config-data
              mountPath: /config
            - name: secret-data
              mountPath: /secrets
          resources:
            limits:
              cpu: 500m
              memory: 1Gi
      restartPolicy: Never
      terminationGracePeriodSeconds: 30