apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: gepardec-sso
  namespace: gepaplexx-cicd-tools
  labels:
    owner: gepaplexx
spec:
  description: ArgoCD Project to deploy a sample application to showcase our staging concept
  # Allow manifests to deploy only from this repositories
  sourceRepos:
    - '*'
  destinations:
    - namespace: '*'
      server: 'https://kubernetes.default.svc'
  clusterResourceWhitelist:
    - group: '*'
      kind: Namespace
  # Enables namespace orphaned resource monitoring.
  orphanedResources:
    warn: true
---
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: gepardec-sso
  namespace: gepaplexx-cicd-tools
  labels:
    owner: gepaplexx
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  generators:
    - list:
        elements:
          # - cluster: kc-dev
          #   url: https://kubernetes.default.svc
          #   branch: main
          - cluster: dev
            url: https://kubernetes.default.svc
            branch: dev
          - cluster: test
            url: https://kubernetes.default.svc
            branch: test
          - cluster: prod
            url: https://kubernetes.default.svc
            branch: prod

  template:
    metadata:
      name: 'gepardec-sso-{{cluster}}'
    spec:
      project: gepardec-sso
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
      source:
        # URL of the repository
        repoURL: git@github.com:gepaplexx-demos/gepardec-sso-ci.git
        # Revision (tag/branch/commit) of the repository (eg HEAD)
        targetRevision: "{{ branch }}"
        # Path within the repository where Kubernetes manifests (and/or Helm, Kustomize, Jsonnet resources) are located
        path: apps/env/{{ cluster }}
      destination:
        server: '{{url}}'
        namespace: 'gepardec-sso-{{cluster}}'