apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.keycloak.postgresql.auth.existingSecret}}
  namespace: {{ .Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: {{ .Release.Service }}
    app.kubernetes.io/instance: {{ .Release.Name }}
    app.kubernetes.io/version: {{ .Chart.Version }}
spec:
  dataFrom:
    - extract:
        key: {{ .Values.env }}
        conversionStrategy: Default
        decodingStrategy: None
  refreshInterval: 12h
  secretStoreRef:
    kind: ClusterSecretStore
    name: gepardec-sso-cluster-store
  target:
    creationPolicy: Owner
    deletionPolicy: Retain
    name: keycloak-config
    template:
      data:
        password: {{`'{{ .db_password }}'`}}
        postgres-password: {{`'{{ .postgres_password }}'`}}


---