name: Deploy via Helm

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        description: Select the environment
        required: true
        options:
          - qa
          - prod

jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    environment:
        name: ${{ inputs.environment }}
        url: https://${{ vars.NAME }}.apps.cloudscale-lpg-2.appuio.cloud
    steps:
      - uses: actions/checkout@v1

      #HELM_PATH contains path to helm chart, for qa: apps/appuio/qa/helm
      - run: helm dependency build ${{ vars.HELM_PATH }}

      - name: 'Deploy'
        uses: 'vimeda/helm@v1.7.0'
        with:
          release: ${{ vars.NAME }}
          namespace: ${{ vars.NAME }}
          chart: ${{ vars.HELM_PATH }}
          token: '${{ github.token }}'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'
  trigger-cli:
    needs: deployment
    runs-on: ubuntu-latest
    steps:
        #This steps needs a GitHub Personal Access Token (PAT) from a user with write access to the repository
        #The PAT currently used is issued to the user tomeindl. If this step fails because of permissions then create a new PAT in Settings
        - name: Trigger Workflow in gepardec-sso-config-ci
          run: |
            # Set the required variables
            repo_owner="gepaplexx-demos" 
            repo_name="gepardec-sso-config-ci"  
            event_type="trigger-workflow-${{ inputs.environment }}" 
            
            curl -L \
              -X POST \
              -H "Accept: application/vnd.github+json" \
              -H "Authorization: Bearer ${{ secrets.PAT }}" \
              -H "X-GitHub-Api-Version: 2022-11-28" \
              https://api.github.com/repos/$repo_owner/$repo_name/dispatches \
              -d "{\"event_type\": \"$event_type\", \"client_payload\": {}}"

