name: Deploy via Helm

on:
  workflow_dispatch:


jobs:
  deployment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1

      - run: helm dependency build apps/appuio/qa/helm

      - name: 'Deploy'
        uses: 'vimeda/helm@v1.7.0'
        with:
          release: 'gepardec-sso-qa'
          namespace: 'gepardec-sso-qa'
          chart: 'apps/appuio/qa/helm'
          token: '${{ github.token }}'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG_QA }}'

