name: Destroy via Helm

on:
  workflow_dispatch:


jobs:
  destroyment:
    runs-on: 'ubuntu-latest'
    steps:
      - uses: actions/checkout@v1

      - name: 'Destroy'
        uses: 'vimeda/helm@v1.7.0'
        with:
          task: 'remove'
          release: ${{ vars.NAME }}
          namespace: ${{ vars.NAME }}
          chart: ${{ vars.HELM_PATH }}
          token: '${{ github.token }}'
        env:
          KUBECONFIG_FILE: '${{ secrets.KUBE_CONFIG }}'